export const AUTH = {
  SEND_SIGNUP_CREDENTIALS: 'SEND_SIGNUP_CREDENTIALS',
  SEND_FORGOT_PASSWORD: 'SEND_FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  SEND_LOGIN_CREDENTIALS: 'SEND_LOGIN_CREDENTIALS',
  ACTIVATE_ACCOUNT: 'ACTIVATE_ACCOUNT',
  SIGNOUT_HANDLER: 'SIGNOUT_HANDLER'
}

export const USER = {
  GET_ACCOUNT_DETAILS: 'GET_ACCOUNT_DETAILS',
  SEND_BASIC_INFO: 'SEND_BASIC_INFO',
  SEND_SHIPPING_INFO: 'SEND_SHIPPING_INFO',
  SEND_BILLING_INFO: 'SEND_BILLING_INFO',
  SEND_PAYMENT_INFO: 'SEND_PAYMENT_INFO',
  UPDATE_FIELD: 'UPDATE_FIELD',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  GET_COUNTRY_LIST: 'GET_COUNTRY_LIST',
  GET_STATE_LIST: 'GET_STATE_LIST',
  FETCH_USER_SESSION_SHOPIFY: 'FETCH_USER_SESSION_SHOPIFY',
  CLEAR_SESSION_SHOPIFY: 'CLEAR_SESSION_SHOPIFY',
  CLEAR_ENTIRE_SHOPIFY_STATE: 'CLEAR_ENTIRE_SHOPIFY_STATE'
}

export const PRODUCTS = {
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
  GET_ALL_VARIABLETYPES: 'GET_ALL_VARIABLETYPES',
  UPDATE_FIELD: 'UPDATE_FIELD',
  UPDATE_PRODUCT_QUERY: 'UPDATE_PRODUCT_QUERY',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPLOAD_PRODUCT_IMAGE: 'UPLOAD_PRODUCT_IMAGE',
  UPLOAD_PRODUCT_VARIANT: 'UPLOAD_PRODUCT_VARIANT',
  DELETE_PRODUCT_IMAGE: 'DELETE_PRODUCT_IMAGE',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  UPDATE_PRODUCT_BASIC_INFO: 'UPDATE_PRODUCT_BASIC_INFO',
  UPDATE_PRODUCT_VARIANT: 'UPDATE_PRODUCT_VARIANT'
}

export const CATEGORY = {
  GET_ALL_CATEGORY: 'GET_ALL_CATEGORY',
  GET_ALL_SUBCATEGORY: 'GET_ALL_SUBCATEGORY',
  GET_ALL_MATERIAL: 'GET_ALL_MATERIAL',
  UPDATE_FIELD: 'UPDATE_FIELD',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  GLOBAL_SEARCH: 'GLOBAL_SEARCH'
}

export const DESIGNTOOL = {
  CLEAR_ADD_ONS_LIST: 'CLEAR_ADD_ONS_LIST',
  REORDER_LAYER: 'REORDER_LAYER',
  LOCK_LAYER: 'LOCK_LAYER',
  UNLOCK_LAYER: 'UNLOCK_LAYER',
  DELETE_LAYER: 'DELETE_LAYER',
  CLEAR_ENTIRE_STATE: 'CLEAR_ENTIRE_STATE',
  ADD_TEXT: 'ADD_TEXT',
  REMOVE_TEXT: 'REMOVE_TEXT',
  CHANGE_TEXT_COLOR: 'CHANGE_TEXT_COLOR',
  CHANGE_TEXT_SIZE: 'CHANGE_TEXT_SIZE',
  CHANGE_TEXT_FONT: 'CHANGE_TEXT_FONT',
  CHANGE_COLOR_VIEW: 'CHANGE_COLOR_VIEW',
  CHANGE_COLOR_ALL: 'CHANGE_COLOR_ALL',
  TOGGLE_APPLY_TO_ALL: 'TOGGLE_APPLY_TO_ALL',
  CHANGE_VIEW: 'CHANGE_VIEW',
  UPDATE_FABRIC_VIEW_LIST: 'UPDATE_FABRIC_VIEW_LIST',
  CHANGE_SELECTED_ADDON: 'CHANGE_SELECTED_ADDON',
  UPDATE_SELECTED_ADDON: 'UPDATE_SELECTED_ADDON',
  UPDATE_ADDONS_LIST: 'UPDATE_ADDONS_LIST',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  ADD_IMAGE_TO_CANVAS: 'ADD_IMAGE_TO_CANVAS',
  SAVE_PRODUCT: 'SAVE_PRODUCT',
  UPDATE_SELECTED_OBJECT_POSITION: 'UPDATE_SELECTED_OBJECT_POSITION',
  CHANGE_PATTERN: 'CHANGE_PATTERN',
  CHANGE_PATTERN_SPACING: 'CHANGE_PATTERN_SPACING',
  CHANGE_IMAGE_DIMENSIONS_FROM_CANVAS: 'GET_IMAGE_DIMENSIONS_FROM_CANVAS',
  ADD_IMAGE_INITIAL_DIMENSIONS: 'ADD_IMAGE_INITIAL_DIMENSIONS',
  ADD_INITIAL_DESIGN: 'ADD_INITIAL_DESIGN',
  SAVE_IMAGE_TO_PHOTO_LIBRARY: 'SAVE_IMAGE_TO_PHOTO_LIBRARY',
  SELECT_PRODUCT_SIZES: 'SELECT_PRODUCT_SIZES',
  STORE_DEFAULT_DESIGNER_JSON: 'STORE_DEFAULT_DESIGNER_JSON',
  SET_CROP_STATUS: 'SET_CROP_STATUS'
}

export const DESIGNMODEL = {
  ADD_BASE_URL: 'ADD_BASE_URL',
  ADD_DESIGNER_JSON: 'ADD_DESIGNER_JSON',
  ADD_PRODUCT_TITLE: 'ADD_PRODUCT_TITLE',
  ADD_MODEL_CONFIG: 'ADD_MODEL_CONFIG'
}
export const ADMIN = {
  UPDATE_FIELD: 'UPDATE_FIELD',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  FETCH_CUSTOMER_LIST: 'FETCH_CUSTOMER_LIST',
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  UPDATE_QUERY: 'UPDATE_QUERY',
  GET_CUSTOMER_DETAILS: 'GET_CUSTOMER_DETAILS',
  UPDATE_CUSTOMER_STATUS: 'UPDATE_CUSTOMER_STATUS',
  UPDATE_WAITINGLIST: 'UPDATE_WAITINGLIST',
  GET_WAITING_LIST_STATUS: 'GET_WAITING_LIST_STATUS',
  ADMIN_ALL_ORDERS: 'ADMIN_ALL_ORDERS',
  ADMIN_ORDER_DETAILS: 'ADMIN_ORDER_DETAILS'
}

export const PRODUCT_LIBRARY = {
  GET_ALL_PRODUCT_LIBRARY: 'GET_ALL_PRODUCT_LIBRARY',
  DUPLICATE_PRODUCT_LIBRARY: 'DUPLICATE_PRODUCT_LIBRARY',
  GET_PRODUCT_LIBRARY_DETAIL: 'GET_PRODUCT_LIBRARY_DETAIL',
  DELETE_PRODUCT_LIBRARY: 'DELETE_PRODUCT_LIBRARY',
  DELETE_PRODUCT_LIBRARY_IMAGE: 'DELETE_PRODUCT_LIBRARY_IMAGE',
  UPDATE_VARIANT: 'UPDATE_VARIANT',
  UPDATE: 'UPDATE',
  UPDATE_DETAILS: 'UPDATE_DETAILS',
  UPDATE_LIABRARY_QUERY: 'UPDATE_LIABRARY_QUERY'
}

export const ORDERS = {
  GET_ALL_ORDERS: 'GET_ALL_ORDERS',
  GET_ORDER_DETAILS: 'GET_ORDER_DETAILS',
  UPDATE_VARIANT: 'UPDATE_VARIANT',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  DELETE_ORDERS: 'DELETE_ORDERS',
  UPDATE_ORDER: 'UPDATE_ORDER',
  CREATE_ORDER: 'CREATE_ORDER',
  SET_DELAY: 'SET_DELAY',
  BULK_ORDER: 'BULK_ORDER',
  ORDER_TEMPLATE: 'ORDER_TEMPLATE',
  ADDRESS_UPDATE: 'ADDRESS_UPDATE',
  DOWNLOAD_DETAILS: 'DOWNLOAD_DETAILS',
  UPDATE_ORDER_QUERY: 'UPDATE_ORDER_QUERY',
  ADD_CART: 'ADD_CART',
  GET_CART_ITEMS: 'GET_CART_ITEMS',
  UPDATE_CART: 'UPDATE_CART',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  PLACE_ORDER: 'PLACE_ORDER',
  GET_SHIPPING_METHODS: 'GET_SHIPPING_METHODS'
}

export const SHOPIFY = {
  GET_SHOPIFY_ACCESS_DATA: 'GET_SHOPIFY_ACCESS_DATA',
  POST_PRODUCT_TO_SHOPIFY: 'POST_PRODUCT_TO_SHOPIFY',
  CLEAR_ENTIRE_SHOPIFY_STATE: 'CLEAR_ENTIRE_SHOPIFY_STATE'
}
export const USER_STORE = {
  GET_ALL_CONNECTED_STORE: 'GET_ALL_CONNECTED_STORE',
  UPDATE_FIELD: 'UPDATE_FIELD',
  GET_INSTALLATION_URL: 'GET_INSTALLATION_URL',
  SAVE_SHOP_INFO: 'SAVE_SHOP_INFO',
  UPDATE_STORE_STATUS: 'UPDATE_STORE_STATUS',
  REMOVE_STORE: 'REMOVE_STORE',
  UPDATE_STORE_UPLOADS_QUERY: 'UPDATE_STORE_UPLOADS_QUERY',
  GET_STORE_UPLOADS_LIST: 'GET_STORE_UPLOADS_LIST',
  RETRY_STORE_UPLOADS: 'RETRY_STORE_UPLOADS'
}
export const FAQ = {
  FAQ_CATEGORY: 'FAQ_CATEGORY',
  ARTICLES: 'ARTICLES'
}
